### ISSUE TITLE
if input.path is a remote url, there will be a download error. (on Windows)

### ISSUE THREAD

**Issue by weicong** [kubb-project/kubb#214]
```js
$ kubb --debug
✔ 💾 Config loaded
✖ Something went wrong

{
  stack: 'ResolverError: Error downloading http://localhost:62114/swagger/v1/swagger.json \n' +
    'socket hang up\n' +
    '    at D:\\Workspace\\ICMS\\v2\\reactjs\\node_modules\\@apidevtools\\json-schema-ref-parser\\lib\\resolvers\\http.js:127:16',
  code: 'ERESOLVER',
  message: 'Error downloading http://localhost:62114/swagger/v1/swagger.json \n' +
    'socket hang up',
  source: 'http://localhost:62114/swagger/v1/swagger.json',
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ECONNRESET',
  name: 'ResolverError',
  toString: [Function: toString]
}


Error: Error downloading http://localhost:62114/swagger/v1/swagger.json 
socket hang up (plugin: swagger-tanstack-query, hook: buildStart)

    at PluginManager.catcher (file:///D:/Workspace/ICMS/v2/reactjs/node_modules/@kubb/core/src/managers/pluginManager/PluginManager.ts:355:5)
    at file:///D:/Workspace/ICMS/v2/reactjs/node_modules/@kubb/core/src/managers/pluginManager/PluginManager.ts:320:9
    at async Promise.all (index 4)
    at async buildImplementation (file:///D:/Workspace/ICMS/v2/reactjs/node_modules/@kubb/core/src/build.ts:71:19)
    at async file:///D:/Workspace/ICMS/v2/reactjs/node_modules/@kubb/core/src/build.ts:83:3 {
  [cause]: {
    stack: 'ResolverError: Error downloading http://localhost:62114/swagger/v1/swagger.json \n' +
      'socket hang up\n' +
      '    at D:\\Workspace\\ICMS\\v2\\reactjs\\node_modules\\@apidevtools\\json-schema-ref-parser\\lib\\resolvers\\http.js:127:16',
    code: 'ERESOLVER',
    message: 'Error downloading http://localhost:62114/swagger/v1/swagger.json \n' +
      'socket hang up',
    source: 'http://localhost:62114/swagger/v1/swagger.json',
    path: null,
    toJSON: [Function: toJSON],
    ioErrorCode: 'ECONNRESET',
    name: 'ResolverError',
    toString: [Function: toString]
  }
}
Done in 7.02s.
```

**Comment by stijnvanhulle** [comment]
Hi, not sure what is going wrong here. For validation and conversions, we are using `@apidevtools/swagger-parser`. Something may be going wrong there when using a local URL.
