### ISSUE TITLE
Zodios Client generates path parameter object instead of string

### ISSUE THREAD

**Issue by meister03** [kubb-project/kubb#487]
### What version of `kubb` is running?

1.10.0

### What platform is your computer?

Linux, Windows

### What steps can reproduce the bug?

**Issue Summary:**

Path parameter is generated as an object on the Zodios client, causing Zodios to expect objects in the path parameters instead of the actual string.

**Reproduction Steps:**

1. Visit the OpenAPI definition at [repro GitHub URL](https://github.com/meister03/kubb-bug-repro/blob/master/kubb/src/resources/openapi.yaml).
2. Observe the path parameter definition for `/users/{userId}` in the OpenAPI definition.
3. Take note of the generated file containing the Zodios client at [wrong generated file](https://github.com/meister03/kubb-bug-repro/blob/8fc75b77fb63acfb2d9db8b7c64e57fc5120c892/kubb/src/generated/zodios.ts#L14).
4. Examine the Zodios client code in the generated file, specifically focusing on how path parameters are generated.
5. Run the provided code with the Zodios client by forking the repo `npm i && npm start`, making a request to `http://localhost:3000/users/12030`.

**Actual Behavior:**

The Zodios client appears to be generating path parameters as objects, causing issues when making requests with string path parameters.

Request on http://localhost:3000/users/12030
```json
{
  context: 'path.GetUserPathParams',
  error: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [],
      message: 'Required'
    }
  ]
}
```

### What is the expected behavior?

The Zodios client should correctly handle path parameters and allow for string values as specified in the OpenAPI definition.

### Swagger/OpenAPI file?

```yaml
openapi: '3.0.0'
info:
  title: Bug Reproduction
  version: 1.0.0
paths:
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get public user details
      description: ...
      operationId: getUser
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User details retrieved successfully
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                        example: 1234343434343
components:
  parameters:
    userId:
      name: userId
      in: path
      description: Executes the action in the context of the specified user.
      required: true
      schema:
        type: string
        example: 1234343434343
```

**Comment by stijnvanhulle** [comment]
With a small change it will generate now the following(https://github.com/kubb-project/kubb/pull/488):

**./zod/getUserSchema**
```
import { z } from 'zod'

export const getUserPathParamsSchema = z.object({ userId: z.string().describe(`Executes the action in the context of the specified user.`) })

/**
 * @description Successful response
 */
export const getUserQueryResponseSchema = z.object({ message: z.string().optional(), user: z.object({ userId: z.string().optional() }).optional() })

```

**zodios.ts**
```
import { makeApi, Zodios } from '@zodios/core'
import { getUserQueryResponseSchema, getUserPathParamsSchema } from './zod/getUserSchema'

const endpoints = makeApi([
  {
    method: 'get',
    path: '/users/:userId',
    description: `...`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'userId',
        description: `Executes the action in the context of the specified user.`,
        type: 'Path',
        schema: getUserPathParamsSchema.shape['userId'],
      },
    ],
    response: getUserQueryResponseSchema,
    errors: [],
  },
])

export const api = new Zodios(endpoints)

export default api


```

**Comment by meister03** [comment]
Follow Up Bug created by the PR
```
Error: Zodios: Multiple body parameters in endpoint '/users/:userId/info'
    at l (file:///workspaces/kubb-bug-repro/kubb/node_modules/@zodios/core/lib/index.mjs:9:1449)
    at z (file:///workspaces/kubb-bug-repro/kubb/node_modules/@zodios/core/lib/index.mjs:9:1540)
    at file:///workspaces/kubb-bug-repro/kubb/dist/generated/zodios.js:3:19
 ```
 
 The shape thing should not account on the body. If you want to test it pull the changes from the bug repro
 ```js
   const endpoints = makeApi([
        {
          method: "put",
          path: "/users/:userId/info",
          description: `...`,
          requestFormat: "json",
          parameters: [
              
          {
            name: "userId",
            description: `Executes the action in the context of the specified user.`,
            type: "Path",
            schema: updateUserInfoPathParamsSchema.shape['userId']
          }
        ,
          {
            name: "checkid",
            description: `Checks something`,
            type: "Query",
            schema: updateUserInfoQueryParamsSchema.shape['checkid']
          }
        ,
          {
            name: "urlcheckid",
            description: `Checks something`,
            type: "Query",
            schema: updateUserInfoQueryParamsSchema.shape['urlcheckid']
          }
        ,
          {
            name: "id",
            description: ``,
            type: "Body",
            schema: updateUserInfoMutationRequestSchema.schema.shape['id']
          }
        ,
          {
            name: "age",
            description: ``,
            type: "Body",
            schema: updateUserInfoMutationRequestSchema.schema.shape['age']
          }
        ,
          {
            name: "name",
            description: ``,
            type: "Body",
            schema: updateUserInfoMutationRequestSchema.schema.shape['name']
          }
        
          ],
          response: updateUserInfoMutationResponseSchema,
          errors: [
              
          ],
      }
      ]);
 
 ```

**Comment by stijnvanhulle** [comment]
`1.11.4` released with a fix for the body :)
